apiVersion: apps/v1
kind: Deployment
metadata:
  name: xread-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xread-api
  template:
    metadata:
      labels:
        app: xread-api
    spec:
      containers:
      - name: xread-api
        image: xread:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: xread-secrets
              key: database-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
