name: CI Pipeline
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-asyncio black mypy
      - name: Run security checks
        run: |
          pip install bandit safety
          bandit -r xread/
          safety check
      - name: Run tests
        run: pytest --cov=xread --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
